### PR TITLE
Paper draft build

### PR DESCRIPTION
**Pull request by alextbradley**
Docs and paper draft have been compiled into build-docs branch. Need to merge these into main, particularly because each time we commit to main, to documentation builds upon the docs files contained in main, which are now out of date.

### CODE REVIEW

**Comment by JimCircadian** [comment]
Hi @alextbradley, nice work! Just had a quick review as I'm in transit, but one think that might be really nice is to remove all the `.DS_Store` files within the repository. They're artifacts from someones MacOS installation. They can be added to the `.gitignore` once removed from the tree (there are a few from what I can tell), but otherwise this looks lush! 👍🏼

**Review by JimCircadian — APPROVED** [review]
Approved, made comment about `.DS_Store` removal

**Comment by CRosieWilliams** [comment]
Looks good to me! I only looked closely at the WAIS example that I provided the data for. The only thing I found wrong was this bit...
"We have a 268 x 315 with, with 3km resolution."
Needs changing for 5km example.
I also noticed these missing references  in the Melt Rates part..
 \eqref{E:plumeparametrization}, rather than \eqref{E:picoparametrization}.
Otherwise, great job!

**Review by CRosieWilliams — APPROVED** [review]
Approve once text for 3km changed to 5km

**Pull request merged**
