### PR TITLE
Rj arthern/issue55

### PR DESCRIPTION
**Pull request by RJArthern**
Hello Alex,

I think this branch will fix the dependency on thickness values outside the mask that David spotted. I've added a test to catch this behaviour too.

Rob

### CODE REVIEW

**Comment by alextbradley** [comment]
Rob, this looks OK to me. Happy to merge. However, I'm can't admit to have a really deep understanding of what is going on in the pos fraction routine, so maybe someone else could also take a look?

**Comment by RJArthern** [comment]
OK. Have asked Rosie to give this a quick look too.

**Comment by CRosieWilliams** [comment]
Yes this looks good to me. Happy for this to be merged.

**Comment by RJArthern** [comment]
OK. I'm going to merge this.

**Pull request merged**
