### PR TITLE
Merging documentation into main

### PR DESCRIPTION
**Pull request by alextbradley**
This was a little bit painful because I've been developing the docs in a different branch ('build-docs'). In the meantime, main has been updated and so the source code changes made in 'build-docs' (necessary for making the docstrings work) now clash. Workflow to get around was:
- Take a new branch from main
- Merge docs from 'build-docs' (does not affect source code)
- Manually fix docstrings in source code on this branch
- Remerge into main (this PR)

### CODE REVIEW

**Comment by JimCircadian** [comment]
Hi @alextbradley, saw this and just wanted to check you know about `git rebase`? If not, let me know and I'll ping you a link if you haven't found one from the mere mention. Apologies if you're already aware of it!

**Comment by alextbradley** [comment]
> Hi @alextbradley, saw this and just wanted to check you know about `git rebase`? If not, let me know and I'll ping you a link if you haven't found one from the mere mention. Apologies if you're already aware of it!

I am not aware - will drop you an email! (Could I have saved myself an afternoon of work??)

**Comment by alextbradley** [comment]
Added continuous integration for unit tests. Added badges for build status for documentation and testing

**Comment by alextbradley** [comment]
@RJArthern all changes now made in response to latest JOSS review (https://github.com/openjournals/joss-reviews/issues/5584)! If you could take a look that would be wonderful :)

**Comment by alextbradley** [comment]
Hey @RJArthern -- could you approve the PR as we discussed last week? I should be able to send off the JOSS responses then

**Review by RJArthern — APPROVED** [review]
OK. Merging.

**Pull request merged**
